### ISSUE TITLE
XML Hatası

### ISSUE THREAD

**Issue by onuryildirimm** [ismetertekin/Codeigniter-3D-SanalPos#2]
Merhaba,
3D şifreyi onayladıktan sonra tüm bankalarda aşağıdaki hatayı veriyor;

Severity: Warning

Message: simplexml_load_string(): Entity: line 4: parser error : Opening and ending tag mismatch: meta line 3 and head

Filename: libraries/Gvp.php

Line Number: 99

Backtrace:

File: /home/link/application/libraries/Gvp.php
Line: 99
Function: simplexml_load_string

File: /home/link/application/controllers/Payment.php
Line: 281
Function: bankResponse

File: /home/link/application/controllers/Payment.php
Line: 148
Function: gvp_callback

File: /home/link/sanalpos2/index.php
Line: 315
Function: require_once

Bu şekilde devam ediyor, yardımcı olabilir misiniz.

**Comment by ismetertekin** [comment]
Hatayı GVP yönteminde almışsın. Bu yöntem garanti bankası için kullanılması gereken yöntemdir. Tüm bankalarda bu hatayı alıyorum demişsin. Diğer bankaları tanımlarken bu yöntemi seçiyorsanız bundan dolayı hata alıyor olabilirsiniz. Açıklama da bankaların hangi yöntemler ile çalıştığını yazdım. Orayı kontrol ederek doğru yöntemi seçip işlemi test edebilirsiniz.

**Comment by onuryildirimm** [comment]
İsmet bey merhaba,5 banka ile sanalpos anlaşmamız var akbank ın bilgileri ile de akbank kart çektiğimdede aynı hatayı alıyorum 
    	
    	

    	iOS için Outlook uygulamasını edinin
    
  




On Tue, Apr 16, 2019 at 7:57 PM +0300, "İsmet ERTEKİN" <notifications@github.com> wrote:












Hatayı GVP yönteminde almışsın. Bu yöntem garanti bankası için kullanılması gereken yöntemdir. Tüm bankalarda bu hatayı alıyorum demişsin. Diğer bankaları tanımlarken bu yöntemi seçiyorsanız bundan dolayı hata alıyor olabilirsiniz. Açıklama da bankaların hangi yöntemler ile çalıştığını yazdım. Orayı kontrol ederek doğru yöntemi seçip işlemi test edebilirsiniz.

**Comment by ismetertekin** [comment]
Akbank için kullanılacak yöntem Nestpay olmalıdır. Eğer Akbank'ta da aynı hatayı alıyorsanız Akbank için de Gvp yöntemini seçmişsiniz demektir.

**Comment by onuryildirimm** [comment]
Akbank için Nestpay yöntemiyle kurulum yapıyorum, banka konusunda sorun yok. Hali hazırda woocommerce sistemimde bu sanal posları kullanıyorum zaten ancak nestpayde olsa gvp de olsa 3d onayından sonra geri dönüşte bu hatayı alıyorum. Dilerseniz link verebilirim sizde deneyebilir, kontrol edebilirsiniz.

**Comment by onuryildirimm** [comment]
İsmet bey sorun api adreslerinden kaynaklanıyormuş, sorun çözüldü. Ancak YKB posnet yöntemi çalışmıyor. Zaten test edilmediğini belirtmişsiniz. Üzerinde çalışıyorum.

**Comment by onuryildirimm** [comment]
Posnetle ilgili hataları düzenledim ve .htaccess dosyasında ufak bir düzeltme yaptım. Sistem sorunsuz çalışıyor tüm bankalarda test edildi.

**Comment by ismetertekin** [comment]
Elinize sağlık onur bey. Posnet için yaptığınız değişiklikleri paylaşırsanız bende projede güncelleme yapayım.

**Comment by onuryildirimm** [comment]
proje üstünde değiştirdim, forklarımdan direk bakabilirsiniz ismet bey. dilerseniz ayrıca da paylaşırım
